# Generated by Django 5.2.6 on 2026-01-21 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(choices=[('rice', 'Rice'), ('wheat', 'Wheat'), ('maize', 'Maize'), ('cotton', 'Cotton'), ('sugarcane', 'Sugarcane'), ('pulses', 'Pulses'), ('vegetables', 'Vegetables')], max_length=20)),
                ('grade', models.CharField(default='Grade A', max_length=50)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='quintal', max_length=20)),
                ('trend_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('state', models.CharField(choices=[('maharashtra', 'Maharashtra'), ('punjab', 'Punjab'), ('uttar_pradesh', 'Uttar Pradesh'), ('madhya_pradesh', 'Madhya Pradesh'), ('karnataka', 'Karnataka'), ('gujarat', 'Gujarat')], max_length=20)),
                ('market_name', models.CharField(choices=[('mumbai', 'APMC Mumbai'), ('pune', 'APMC Pune'), ('nagpur', 'APMC Nagpur'), ('nashik', 'APMC Nashik'), ('aurangabad', 'APMC Aurangabad')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=50)),
                ('demand_level', models.CharField(max_length=20)),
                ('change_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('forecast_date', models.DateField()),
            ],
            options={
                'ordering': ['forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='MarketNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('category', models.CharField(choices=[('policy', 'Policy'), ('weather', 'Weather'), ('market', 'Market'), ('technology', 'Technology'), ('export', 'Export')], max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
                ('url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Market News',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alert_type', models.CharField(choices=[('above', 'Price Above'), ('below', 'Price Below'), ('change', 'Price Change %')], max_length=10)),
                ('notification_method', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
